services:
  postgres:
    container_name: postgres
    image: postgres:17-alpine
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data:Z
